### ISSUE TITLE
Remove Access Modifiers from Interfaces

### ISSUE THREAD

**Issue by kizivat** [monster-slayers/web-is#41]
Btw vsimol som si ze davate v interfacoch encapsulation modifiers. V rozhrani by sa nemala definovat, tak ked budete najblzsie commitovat nieco by ste to mohli odstranit :)

- [x] ClientRequestRepository
- [x] HeroRepository
- [x] JobRepository
- [x] MonsterTypeRepository
- [x] UserRepository

**Comment by tomasrichter** [comment]
User/Hero done
